### ISSUE TITLE
ReferenceError: sound used in its own declaration

### ISSUE THREAD

**Issue by LightSeek3r** [robonyong/react-split-flap-display#16]
In **CharacterComponent**, you call sound inside its declaration. That's a no-go error on my end, could you please separate _declaration_ and _usage_? Thanks

```
const sound = React__namespace.useMemo(() => {
        if (sound) { // <- Uncaught ReferenceError: Cannot access 'sound' before initialization
            sound.unload();
        }
```

**Comment by robonyong** [comment]
Huh, would've thought my linter/transpiler would catch that. Repro'd in a clean project & released 0.4.1 -- new version seems to resolve this on my end

**Comment by robonyong** [comment]
Closing for now -- if 0.4.1 does not work for you please open another issue

**Comment by LightSeek3r** [comment]
Sorry for the late response, and thank you for your reactivity.
0.4.1 works like a charm, great job champ!
